# inspired by https://www.baeldung.com/ops/multiple-dockerfiles
# also inspired by https://andrewhalil.com/2022/01/21/cross-container-api-calls-in-a-docker-image/

services:
  team_chatbot:
    build: ./students-assitants
    env_file:
      - ./students-assitants/discord.env
    ports:
     - "3978:3978"
     - "3979:3979"
    depends_on:
      - flask_app_llm
  flask_app_llm:
    build: ./flask_chatbot_student_assitants
    ports:
      - "5000:5000"